// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shortlink/v1/shortlink.proto

package shortlinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortLinkStatus int32

const (
	ShortLinkStatus_SHORT_LINK_STATUS_UNSPECIFIED ShortLinkStatus = 0
	ShortLinkStatus_SHORT_LINK_STATUS_ACTIVE      ShortLinkStatus = 1
	ShortLinkStatus_SHORT_LINK_STATUS_EXPIRED     ShortLinkStatus = 2
	ShortLinkStatus_SHORT_LINK_STATUS_NOT_FOUND   ShortLinkStatus = 3
)

// Enum value maps for ShortLinkStatus.
var (
	ShortLinkStatus_name = map[int32]string{
		0: "SHORT_LINK_STATUS_UNSPECIFIED",
		1: "SHORT_LINK_STATUS_ACTIVE",
		2: "SHORT_LINK_STATUS_EXPIRED",
		3: "SHORT_LINK_STATUS_NOT_FOUND",
	}
	ShortLinkStatus_value = map[string]int32{
		"SHORT_LINK_STATUS_UNSPECIFIED": 0,
		"SHORT_LINK_STATUS_ACTIVE":      1,
		"SHORT_LINK_STATUS_EXPIRED":     2,
		"SHORT_LINK_STATUS_NOT_FOUND":   3,
	}
)

func (x ShortLinkStatus) Enum() *ShortLinkStatus {
	p := new(ShortLinkStatus)
	*p = x
	return p
}

func (x ShortLinkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShortLinkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shortlink_v1_shortlink_proto_enumTypes[0].Descriptor()
}

func (ShortLinkStatus) Type() protoreflect.EnumType {
	return &file_shortlink_v1_shortlink_proto_enumTypes[0]
}

func (x ShortLinkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShortLinkStatus.Descriptor instead.
func (ShortLinkStatus) EnumDescriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{0}
}

type CreateShortUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginUrl     string                 `protobuf:"bytes,1,opt,name=origin_url,json=originUrl,proto3" json:"origin_url,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortUrlRequest) Reset() {
	*x = CreateShortUrlRequest{}
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortUrlRequest) ProtoMessage() {}

func (x *CreateShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortUrlRequest.ProtoReflect.Descriptor instead.
func (*CreateShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortUrlRequest) GetOriginUrl() string {
	if x != nil {
		return x.OriginUrl
	}
	return ""
}

func (x *CreateShortUrlRequest) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type CreateShortUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortUrlResponse) Reset() {
	*x = CreateShortUrlResponse{}
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortUrlResponse) ProtoMessage() {}

func (x *CreateShortUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortUrlResponse.ProtoReflect.Descriptor instead.
func (*CreateShortUrlResponse) Descriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortUrlResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type GetOriginUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Referer       string                 `protobuf:"bytes,4,opt,name=referer,proto3" json:"referer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginUrlRequest) Reset() {
	*x = GetOriginUrlRequest{}
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginUrlRequest) ProtoMessage() {}

func (x *GetOriginUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginUrlRequest.ProtoReflect.Descriptor instead.
func (*GetOriginUrlRequest) Descriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginUrlRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *GetOriginUrlRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *GetOriginUrlRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *GetOriginUrlRequest) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

type GetOriginUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginUrl     string                 `protobuf:"bytes,1,opt,name=origin_url,json=originUrl,proto3" json:"origin_url,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Status        ShortLinkStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=shortlink.v1.ShortLinkStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginUrlResponse) Reset() {
	*x = GetOriginUrlResponse{}
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginUrlResponse) ProtoMessage() {}

func (x *GetOriginUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginUrlResponse.ProtoReflect.Descriptor instead.
func (*GetOriginUrlResponse) Descriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginUrlResponse) GetOriginUrl() string {
	if x != nil {
		return x.OriginUrl
	}
	return ""
}

func (x *GetOriginUrlResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetOriginUrlResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *GetOriginUrlResponse) GetStatus() ShortLinkStatus {
	if x != nil {
		return x.Status
	}
	return ShortLinkStatus_SHORT_LINK_STATUS_UNSPECIFIED
}

type GetShortUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortUrlRequest) Reset() {
	*x = GetShortUrlRequest{}
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortUrlRequest) ProtoMessage() {}

func (x *GetShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortUrlRequest.ProtoReflect.Descriptor instead.
func (*GetShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{4}
}

func (x *GetShortUrlRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type GetShortUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	OriginUrl     string                 `protobuf:"bytes,2,opt,name=origin_url,json=originUrl,proto3" json:"origin_url,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Status        ShortLinkStatus        `protobuf:"varint,5,opt,name=status,proto3,enum=shortlink.v1.ShortLinkStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortUrlResponse) Reset() {
	*x = GetShortUrlResponse{}
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortUrlResponse) ProtoMessage() {}

func (x *GetShortUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortUrlResponse.ProtoReflect.Descriptor instead.
func (*GetShortUrlResponse) Descriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{5}
}

func (x *GetShortUrlResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *GetShortUrlResponse) GetOriginUrl() string {
	if x != nil {
		return x.OriginUrl
	}
	return ""
}

func (x *GetShortUrlResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetShortUrlResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *GetShortUrlResponse) GetStatus() ShortLinkStatus {
	if x != nil {
		return x.Status
	}
	return ShortLinkStatus_SHORT_LINK_STATUS_UNSPECIFIED
}

type DeleteShortUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortUrlRequest) Reset() {
	*x = DeleteShortUrlRequest{}
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortUrlRequest) ProtoMessage() {}

func (x *DeleteShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortUrlRequest.ProtoReflect.Descriptor instead.
func (*DeleteShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteShortUrlRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type DeleteShortUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortUrlResponse) Reset() {
	*x = DeleteShortUrlResponse{}
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortUrlResponse) ProtoMessage() {}

func (x *DeleteShortUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortUrlResponse.ProtoReflect.Descriptor instead.
func (*DeleteShortUrlResponse) Descriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteShortUrlResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type StatsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsItem) Reset() {
	*x = StatsItem{}
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsItem) ProtoMessage() {}

func (x *StatsItem) ProtoReflect() protoreflect.Message {
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsItem.ProtoReflect.Descriptor instead.
func (*StatsItem) Descriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{8}
}

func (x *StatsItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StatsItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetShortUrlStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortUrlStatsRequest) Reset() {
	*x = GetShortUrlStatsRequest{}
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortUrlStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortUrlStatsRequest) ProtoMessage() {}

func (x *GetShortUrlStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortUrlStatsRequest.ProtoReflect.Descriptor instead.
func (*GetShortUrlStatsRequest) Descriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{9}
}

func (x *GetShortUrlStatsRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type GetShortUrlStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	Pv            int64                  `protobuf:"varint,2,opt,name=pv,proto3" json:"pv,omitempty"`
	Uv            int64                  `protobuf:"varint,3,opt,name=uv,proto3" json:"uv,omitempty"`
	LastVisitedAt int64                  `protobuf:"varint,4,opt,name=last_visited_at,json=lastVisitedAt,proto3" json:"last_visited_at,omitempty"`
	TopReferers   []*StatsItem           `protobuf:"bytes,5,rep,name=top_referers,json=topReferers,proto3" json:"top_referers,omitempty"`
	TopUserAgents []*StatsItem           `protobuf:"bytes,6,rep,name=top_user_agents,json=topUserAgents,proto3" json:"top_user_agents,omitempty"`
	Status        ShortLinkStatus        `protobuf:"varint,7,opt,name=status,proto3,enum=shortlink.v1.ShortLinkStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortUrlStatsResponse) Reset() {
	*x = GetShortUrlStatsResponse{}
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortUrlStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortUrlStatsResponse) ProtoMessage() {}

func (x *GetShortUrlStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortlink_v1_shortlink_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortUrlStatsResponse.ProtoReflect.Descriptor instead.
func (*GetShortUrlStatsResponse) Descriptor() ([]byte, []int) {
	return file_shortlink_v1_shortlink_proto_rawDescGZIP(), []int{10}
}

func (x *GetShortUrlStatsResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *GetShortUrlStatsResponse) GetPv() int64 {
	if x != nil {
		return x.Pv
	}
	return 0
}

func (x *GetShortUrlStatsResponse) GetUv() int64 {
	if x != nil {
		return x.Uv
	}
	return 0
}

func (x *GetShortUrlStatsResponse) GetLastVisitedAt() int64 {
	if x != nil {
		return x.LastVisitedAt
	}
	return 0
}

func (x *GetShortUrlStatsResponse) GetTopReferers() []*StatsItem {
	if x != nil {
		return x.TopReferers
	}
	return nil
}

func (x *GetShortUrlStatsResponse) GetTopUserAgents() []*StatsItem {
	if x != nil {
		return x.TopUserAgents
	}
	return nil
}

func (x *GetShortUrlStatsResponse) GetStatus() ShortLinkStatus {
	if x != nil {
		return x.Status
	}
	return ShortLinkStatus_SHORT_LINK_STATUS_UNSPECIFIED
}

var File_shortlink_v1_shortlink_proto protoreflect.FileDescriptor

const file_shortlink_v1_shortlink_proto_rawDesc = "" +
	"\n" +
	"\x1cshortlink/v1/shortlink.proto\x12\fshortlink.v1\"S\n" +
	"\x15CreateShortUrlRequest\x12\x1d\n" +
	"\n" +
	"origin_url\x18\x01 \x01(\tR\toriginUrl\x12\x1b\n" +
	"\texpire_at\x18\x02 \x01(\x03R\bexpireAt\"7\n" +
	"\x16CreateShortUrlResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"\x8a\x01\n" +
	"\x13GetOriginUrlRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x18\n" +
	"\areferer\x18\x04 \x01(\tR\areferer\"\xa8\x01\n" +
	"\x14GetOriginUrlResponse\x12\x1d\n" +
	"\n" +
	"origin_url\x18\x01 \x01(\tR\toriginUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\texpire_at\x18\x03 \x01(\x03R\bexpireAt\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.shortlink.v1.ShortLinkStatusR\x06status\"3\n" +
	"\x12GetShortUrlRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"\xc6\x01\n" +
	"\x13GetShortUrlResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1d\n" +
	"\n" +
	"origin_url\x18\x02 \x01(\tR\toriginUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\x03R\bexpireAt\x125\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1d.shortlink.v1.ShortLinkStatusR\x06status\"6\n" +
	"\x15DeleteShortUrlRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"2\n" +
	"\x16DeleteShortUrlResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"7\n" +
	"\tStatsItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"8\n" +
	"\x17GetShortUrlStatsRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"\xb5\x02\n" +
	"\x18GetShortUrlStatsResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x0e\n" +
	"\x02pv\x18\x02 \x01(\x03R\x02pv\x12\x0e\n" +
	"\x02uv\x18\x03 \x01(\x03R\x02uv\x12&\n" +
	"\x0flast_visited_at\x18\x04 \x01(\x03R\rlastVisitedAt\x12:\n" +
	"\ftop_referers\x18\x05 \x03(\v2\x17.shortlink.v1.StatsItemR\vtopReferers\x12?\n" +
	"\x0ftop_user_agents\x18\x06 \x03(\v2\x17.shortlink.v1.StatsItemR\rtopUserAgents\x125\n" +
	"\x06status\x18\a \x01(\x0e2\x1d.shortlink.v1.ShortLinkStatusR\x06status*\x92\x01\n" +
	"\x0fShortLinkStatus\x12!\n" +
	"\x1dSHORT_LINK_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SHORT_LINK_STATUS_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19SHORT_LINK_STATUS_EXPIRED\x10\x02\x12\x1f\n" +
	"\x1bSHORT_LINK_STATUS_NOT_FOUND\x10\x032\xda\x03\n" +
	"\x10ShortLinkService\x12[\n" +
	"\x0eCreateShortUrl\x12#.shortlink.v1.CreateShortUrlRequest\x1a$.shortlink.v1.CreateShortUrlResponse\x12U\n" +
	"\fGetOriginUrl\x12!.shortlink.v1.GetOriginUrlRequest\x1a\".shortlink.v1.GetOriginUrlResponse\x12R\n" +
	"\vGetShortUrl\x12 .shortlink.v1.GetShortUrlRequest\x1a!.shortlink.v1.GetShortUrlResponse\x12[\n" +
	"\x0eDeleteShortUrl\x12#.shortlink.v1.DeleteShortUrlRequest\x1a$.shortlink.v1.DeleteShortUrlResponse\x12a\n" +
	"\x10GetShortUrlStats\x12%.shortlink.v1.GetShortUrlStatsRequest\x1a&.shortlink.v1.GetShortUrlStatsResponseB(Z&short_url/api/shortlink/v1;shortlinkv1b\x06proto3"

var (
	file_shortlink_v1_shortlink_proto_rawDescOnce sync.Once
	file_shortlink_v1_shortlink_proto_rawDescData []byte
)

func file_shortlink_v1_shortlink_proto_rawDescGZIP() []byte {
	file_shortlink_v1_shortlink_proto_rawDescOnce.Do(func() {
		file_shortlink_v1_shortlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortlink_v1_shortlink_proto_rawDesc), len(file_shortlink_v1_shortlink_proto_rawDesc)))
	})
	return file_shortlink_v1_shortlink_proto_rawDescData
}

var file_shortlink_v1_shortlink_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shortlink_v1_shortlink_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_shortlink_v1_shortlink_proto_goTypes = []any{
	(ShortLinkStatus)(0),             // 0: shortlink.v1.ShortLinkStatus
	(*CreateShortUrlRequest)(nil),    // 1: shortlink.v1.CreateShortUrlRequest
	(*CreateShortUrlResponse)(nil),   // 2: shortlink.v1.CreateShortUrlResponse
	(*GetOriginUrlRequest)(nil),      // 3: shortlink.v1.GetOriginUrlRequest
	(*GetOriginUrlResponse)(nil),     // 4: shortlink.v1.GetOriginUrlResponse
	(*GetShortUrlRequest)(nil),       // 5: shortlink.v1.GetShortUrlRequest
	(*GetShortUrlResponse)(nil),      // 6: shortlink.v1.GetShortUrlResponse
	(*DeleteShortUrlRequest)(nil),    // 7: shortlink.v1.DeleteShortUrlRequest
	(*DeleteShortUrlResponse)(nil),   // 8: shortlink.v1.DeleteShortUrlResponse
	(*StatsItem)(nil),                // 9: shortlink.v1.StatsItem
	(*GetShortUrlStatsRequest)(nil),  // 10: shortlink.v1.GetShortUrlStatsRequest
	(*GetShortUrlStatsResponse)(nil), // 11: shortlink.v1.GetShortUrlStatsResponse
}
var file_shortlink_v1_shortlink_proto_depIdxs = []int32{
	0,  // 0: shortlink.v1.GetOriginUrlResponse.status:type_name -> shortlink.v1.ShortLinkStatus
	0,  // 1: shortlink.v1.GetShortUrlResponse.status:type_name -> shortlink.v1.ShortLinkStatus
	9,  // 2: shortlink.v1.GetShortUrlStatsResponse.top_referers:type_name -> shortlink.v1.StatsItem
	9,  // 3: shortlink.v1.GetShortUrlStatsResponse.top_user_agents:type_name -> shortlink.v1.StatsItem
	0,  // 4: shortlink.v1.GetShortUrlStatsResponse.status:type_name -> shortlink.v1.ShortLinkStatus
	1,  // 5: shortlink.v1.ShortLinkService.CreateShortUrl:input_type -> shortlink.v1.CreateShortUrlRequest
	3,  // 6: shortlink.v1.ShortLinkService.GetOriginUrl:input_type -> shortlink.v1.GetOriginUrlRequest
	5,  // 7: shortlink.v1.ShortLinkService.GetShortUrl:input_type -> shortlink.v1.GetShortUrlRequest
	7,  // 8: shortlink.v1.ShortLinkService.DeleteShortUrl:input_type -> shortlink.v1.DeleteShortUrlRequest
	10, // 9: shortlink.v1.ShortLinkService.GetShortUrlStats:input_type -> shortlink.v1.GetShortUrlStatsRequest
	2,  // 10: shortlink.v1.ShortLinkService.CreateShortUrl:output_type -> shortlink.v1.CreateShortUrlResponse
	4,  // 11: shortlink.v1.ShortLinkService.GetOriginUrl:output_type -> shortlink.v1.GetOriginUrlResponse
	6,  // 12: shortlink.v1.ShortLinkService.GetShortUrl:output_type -> shortlink.v1.GetShortUrlResponse
	8,  // 13: shortlink.v1.ShortLinkService.DeleteShortUrl:output_type -> shortlink.v1.DeleteShortUrlResponse
	11, // 14: shortlink.v1.ShortLinkService.GetShortUrlStats:output_type -> shortlink.v1.GetShortUrlStatsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_shortlink_v1_shortlink_proto_init() }
func file_shortlink_v1_shortlink_proto_init() {
	if File_shortlink_v1_shortlink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortlink_v1_shortlink_proto_rawDesc), len(file_shortlink_v1_shortlink_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortlink_v1_shortlink_proto_goTypes,
		DependencyIndexes: file_shortlink_v1_shortlink_proto_depIdxs,
		EnumInfos:         file_shortlink_v1_shortlink_proto_enumTypes,
		MessageInfos:      file_shortlink_v1_shortlink_proto_msgTypes,
	}.Build()
	File_shortlink_v1_shortlink_proto = out.File
	file_shortlink_v1_shortlink_proto_goTypes = nil
	file_shortlink_v1_shortlink_proto_depIdxs = nil
}
