// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: shortlink/v1/shortlink.proto

package shortlinkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShortLinkService_CreateShortUrl_FullMethodName   = "/shortlink.v1.ShortLinkService/CreateShortUrl"
	ShortLinkService_GetOriginUrl_FullMethodName     = "/shortlink.v1.ShortLinkService/GetOriginUrl"
	ShortLinkService_GetShortUrl_FullMethodName      = "/shortlink.v1.ShortLinkService/GetShortUrl"
	ShortLinkService_DeleteShortUrl_FullMethodName   = "/shortlink.v1.ShortLinkService/DeleteShortUrl"
	ShortLinkService_GetShortUrlStats_FullMethodName = "/shortlink.v1.ShortLinkService/GetShortUrlStats"
)

// ShortLinkServiceClient is the client API for ShortLinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortLinkServiceClient interface {
	CreateShortUrl(ctx context.Context, in *CreateShortUrlRequest, opts ...grpc.CallOption) (*CreateShortUrlResponse, error)
	GetOriginUrl(ctx context.Context, in *GetOriginUrlRequest, opts ...grpc.CallOption) (*GetOriginUrlResponse, error)
	GetShortUrl(ctx context.Context, in *GetShortUrlRequest, opts ...grpc.CallOption) (*GetShortUrlResponse, error)
	DeleteShortUrl(ctx context.Context, in *DeleteShortUrlRequest, opts ...grpc.CallOption) (*DeleteShortUrlResponse, error)
	GetShortUrlStats(ctx context.Context, in *GetShortUrlStatsRequest, opts ...grpc.CallOption) (*GetShortUrlStatsResponse, error)
}

type shortLinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortLinkServiceClient(cc grpc.ClientConnInterface) ShortLinkServiceClient {
	return &shortLinkServiceClient{cc}
}

func (c *shortLinkServiceClient) CreateShortUrl(ctx context.Context, in *CreateShortUrlRequest, opts ...grpc.CallOption) (*CreateShortUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShortUrlResponse)
	err := c.cc.Invoke(ctx, ShortLinkService_CreateShortUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortLinkServiceClient) GetOriginUrl(ctx context.Context, in *GetOriginUrlRequest, opts ...grpc.CallOption) (*GetOriginUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOriginUrlResponse)
	err := c.cc.Invoke(ctx, ShortLinkService_GetOriginUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortLinkServiceClient) GetShortUrl(ctx context.Context, in *GetShortUrlRequest, opts ...grpc.CallOption) (*GetShortUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShortUrlResponse)
	err := c.cc.Invoke(ctx, ShortLinkService_GetShortUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortLinkServiceClient) DeleteShortUrl(ctx context.Context, in *DeleteShortUrlRequest, opts ...grpc.CallOption) (*DeleteShortUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShortUrlResponse)
	err := c.cc.Invoke(ctx, ShortLinkService_DeleteShortUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortLinkServiceClient) GetShortUrlStats(ctx context.Context, in *GetShortUrlStatsRequest, opts ...grpc.CallOption) (*GetShortUrlStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShortUrlStatsResponse)
	err := c.cc.Invoke(ctx, ShortLinkService_GetShortUrlStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortLinkServiceServer is the server API for ShortLinkService service.
// All implementations must embed UnimplementedShortLinkServiceServer
// for forward compatibility.
type ShortLinkServiceServer interface {
	CreateShortUrl(context.Context, *CreateShortUrlRequest) (*CreateShortUrlResponse, error)
	GetOriginUrl(context.Context, *GetOriginUrlRequest) (*GetOriginUrlResponse, error)
	GetShortUrl(context.Context, *GetShortUrlRequest) (*GetShortUrlResponse, error)
	DeleteShortUrl(context.Context, *DeleteShortUrlRequest) (*DeleteShortUrlResponse, error)
	GetShortUrlStats(context.Context, *GetShortUrlStatsRequest) (*GetShortUrlStatsResponse, error)
	mustEmbedUnimplementedShortLinkServiceServer()
}

// UnimplementedShortLinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShortLinkServiceServer struct{}

func (UnimplementedShortLinkServiceServer) CreateShortUrl(context.Context, *CreateShortUrlRequest) (*CreateShortUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShortUrl not implemented")
}
func (UnimplementedShortLinkServiceServer) GetOriginUrl(context.Context, *GetOriginUrlRequest) (*GetOriginUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOriginUrl not implemented")
}
func (UnimplementedShortLinkServiceServer) GetShortUrl(context.Context, *GetShortUrlRequest) (*GetShortUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShortUrl not implemented")
}
func (UnimplementedShortLinkServiceServer) DeleteShortUrl(context.Context, *DeleteShortUrlRequest) (*DeleteShortUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShortUrl not implemented")
}
func (UnimplementedShortLinkServiceServer) GetShortUrlStats(context.Context, *GetShortUrlStatsRequest) (*GetShortUrlStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShortUrlStats not implemented")
}
func (UnimplementedShortLinkServiceServer) mustEmbedUnimplementedShortLinkServiceServer() {}
func (UnimplementedShortLinkServiceServer) testEmbeddedByValue()                          {}

// UnsafeShortLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortLinkServiceServer will
// result in compilation errors.
type UnsafeShortLinkServiceServer interface {
	mustEmbedUnimplementedShortLinkServiceServer()
}

func RegisterShortLinkServiceServer(s grpc.ServiceRegistrar, srv ShortLinkServiceServer) {
	// If the following call pancis, it indicates UnimplementedShortLinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShortLinkService_ServiceDesc, srv)
}

func _ShortLinkService_CreateShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShortUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortLinkServiceServer).CreateShortUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortLinkService_CreateShortUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortLinkServiceServer).CreateShortUrl(ctx, req.(*CreateShortUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortLinkService_GetOriginUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOriginUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortLinkServiceServer).GetOriginUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortLinkService_GetOriginUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortLinkServiceServer).GetOriginUrl(ctx, req.(*GetOriginUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortLinkService_GetShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShortUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortLinkServiceServer).GetShortUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortLinkService_GetShortUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortLinkServiceServer).GetShortUrl(ctx, req.(*GetShortUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortLinkService_DeleteShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShortUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortLinkServiceServer).DeleteShortUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortLinkService_DeleteShortUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortLinkServiceServer).DeleteShortUrl(ctx, req.(*DeleteShortUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortLinkService_GetShortUrlStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShortUrlStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortLinkServiceServer).GetShortUrlStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortLinkService_GetShortUrlStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortLinkServiceServer).GetShortUrlStats(ctx, req.(*GetShortUrlStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortLinkService_ServiceDesc is the grpc.ServiceDesc for ShortLinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortLinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shortlink.v1.ShortLinkService",
	HandlerType: (*ShortLinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShortUrl",
			Handler:    _ShortLinkService_CreateShortUrl_Handler,
		},
		{
			MethodName: "GetOriginUrl",
			Handler:    _ShortLinkService_GetOriginUrl_Handler,
		},
		{
			MethodName: "GetShortUrl",
			Handler:    _ShortLinkService_GetShortUrl_Handler,
		},
		{
			MethodName: "DeleteShortUrl",
			Handler:    _ShortLinkService_DeleteShortUrl_Handler,
		},
		{
			MethodName: "GetShortUrlStats",
			Handler:    _ShortLinkService_GetShortUrlStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shortlink/v1/shortlink.proto",
}
