FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /web-server ./web

FROM alpine:3.21
COPY --from=builder /web-server /usr/local/bin/web-server
COPY web/config/config.template.yaml /etc/short_url/config.yaml
CMD ["web-server"]
