FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /web-server ./cmd/web

FROM alpine:3.21
COPY --from=builder /web-server /usr/local/bin/web-server
COPY configs/web.yaml /etc/short_url/web.yaml
CMD ["web-server"]
